run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exportloopref
    - forbidigo
    - gci
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - cyclop
    - dogsled
    - errorlint
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - gomnd
    - gosec
    - interfacebloat
    - loggercheck
    - maintidx
    - nestif
    - nonamedreturns
    - reassign
    - revive
    - stylecheck
    - thelper
    - wrapcheck
    - wsl
