name: GolangCI

on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  run_golangci:
    name: Run GolangCI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Go 1.21'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Display Go version
        run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54