name: Test

on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Go 1.18'
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get .

      - name: run test
        run: make test